export const COMPONENT_ICONS: Record<string, string> = {
  vpc: "🌐",
  subnet: "📦",
  ec2: "💻",
  rds: "🗄️",
  s3: "🪣",
  elb: "⚖️",
  eks: "☸️",
  lambda: "⚡",
  apigateway: "🔌",
  cloudfront: "🌩️",
  route53: "🗺️",
  sqs: "📨",
  sns: "📢",
  iam: "🔐",
  nat_gateway: "🔄",
  internet_gateway: "🌍",
  security_group: "🛡️",
  virtual_network: "🌐",
  vm: "💻",
  sql_database: "🗄️",
  blob_storage: "🪣",
  aks: "☸️",
  functions: "⚡",
  app_gateway: "⚖️",
  key_vault: "🔑",
  vnet: "🌐",
  gke: "☸️",
  cloud_sql: "🗄️",
  cloud_storage: "🪣",
  cloud_functions: "⚡",
  cloud_run: "🏃",
  bigquery: "📊",
  pub_sub: "📨",
  load_balancer: "⚖️",
  custom: "⚙️",
};

export const COMPONENT_LABELS: Record<string, string> = {
  vpc: "VPC",
  subnet: "Subnet",
  ec2: "EC2",
  rds: "RDS",
  s3: "S3 Bucket",
  elb: "Load Balancer",
  eks: "EKS",
  lambda: "Lambda",
  apigateway: "API Gateway",
  cloudfront: "CloudFront",
  route53: "Route 53",
  sqs: "SQS",
  sns: "SNS",
  iam: "IAM",
  nat_gateway: "NAT Gateway",
  internet_gateway: "Internet GW",
  security_group: "Security Group",
  virtual_network: "Virtual Network",
  vm: "Virtual Machine",
  sql_database: "SQL Database",
  blob_storage: "Blob Storage",
  aks: "AKS",
  functions: "Functions",
  app_gateway: "App Gateway",
  key_vault: "Key Vault",
  vnet: "VNet",
  gke: "GKE",
  cloud_sql: "Cloud SQL",
  cloud_storage: "Cloud Storage",
  cloud_functions: "Cloud Functions",
  cloud_run: "Cloud Run",
  bigquery: "BigQuery",
  pub_sub: "Pub/Sub",
  load_balancer: "Load Balancer",
  custom: "Custom",
};

export const PROVIDER_COLORS: Record<string, string> = {
  aws: "#FF9900",
  azure: "#0078D4",
  gcp: "#4285F4",
  multi: "#00d4ff",
};

export const PROVIDER_LABELS: Record<string, string> = {
  aws: "AWS",
  azure: "Azure",
  gcp: "GCP",
  multi: "Multi",
};
